### ISSUE TITLE
Left Side Bar

### ISSUE THREAD

**Issue by SDWT** [Infarh/WebStore_11_19_1#25]
https://github.com/Infarh/WebStore_11_19_1/blob/fd8eb95015953e7bc6b3515093686ed6fb887713/WebStore/Views/Home/Index.cshtml#L15

Можно ещё одно частичное представление вынести (подсмотрел в методичке).

**Comment by Infarh** [comment]
👍

**Comment by micolla** [comment]
А оно много где встречается?
