### ISSUE TITLE
Проверка на null выдаёт ошибку по выходу за пределы перечисления.

### ISSUE THREAD

**Issue by SDWT** [Infarh/WebStore_11_19_1#31]
https://github.com/Infarh/WebStore_11_19_1/blob/6c7a3c640b9515a5b5124faad776250cd66accf7/WebStore/Controllers/EmployeesController.cs#L79-L80

Предлагаю заменить ошибку на:
`throw new ArgumentNullException(nameof(Employee));`

**Comment by Infarh** [comment]
Как воспроизвести?

**Comment by SDWT** [comment]
Сейчас без прямого Post запроса никак. Думаю сейчас это недостижимый код.

**Comment by Infarh** [comment]
Не подтверждено
